"use client";
import { useState, useEffect, Suspense } from "react";
import { useRouter } from "next/navigation";
import { Calendar, Clock, Loader2, Video, ArrowRight, ShieldCheck, Terminal, Network } from "lucide-react";
import DecodeText from "../components/DecodeText";
import RevealWrapper from "../components/RevealWrapper";
import MagneticWrapper from "../components/MagneticWrapper";

function ScheduleLogic() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [minDate, setMinDate] = useState("");
  
  const [scheduleForm, setScheduleForm] = useState({
    name: "",
    email: "",
    date: "",
    time: "09:00 AM",
    topic: "Network Architecture Review",
    notes: ""
  });

  // Ensure users can only select future dates
  useEffect(() => {
    const today = new Date();
    // Add 1 day to require at least 24h notice
    today.setDate(today.getDate() + 1);
    setMinDate(today.toISOString().split("T")[0]);
  }, []);

  const handleScheduleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
TAKUMI TECH - CONSULTATION SECURED
=========================================
CLIENT INFORMATION
-----------------------------------------
Name:     ${scheduleForm.name}
Email:    ${scheduleForm.email}

TEMPORAL VECTORS
-----------------------------------------
Requested Date:  ${scheduleForm.date}
Requested Time:  ${scheduleForm.time} (SAST)

OPERATIONAL SCOPE
-----------------------------------------
Topic:    ${scheduleForm.topic}
Briefing: ${scheduleForm.notes || "No additional parameters provided."}
=========================================
System Generated by Takumitech.co.za
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", scheduleForm.name || "Takumi Client");
      payload.append("email", scheduleForm.email || "no-reply@takumitech.co.za");
      payload.append("subject", `Consultation Request: ${scheduleForm.date} - ${scheduleForm.name}`);
      payload.append("from_name", "Takumi Tech Scheduling");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: payload });
      const result = await response.json();
      
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to secure time slot. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="w-full flex flex-col items-center relative z-10 px-4 md:px-6">
      
      {/* --------------------------------------------------------- */}
      {/* HEADER SECTION */}
      {/* --------------------------------------------------------- */}
      <header className="w-full max-w-5xl mb-16 text-center mt-10">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 mb-6 backdrop-blur-md">
          <Calendar className="w-4 h-4 text-blue-400" />
          <span className="text-xs font-mono text-blue-300 uppercase tracking-widest">Architectural Consultation</span>
        </div>
        <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase mb-6 leading-none">
          <DecodeText text="Secure A" /> <br className="md:hidden" />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-indigo-400 drop-shadow-[0_0_30px_rgba(96,165,250,0.3)]">
            <DecodeText text="Time Vector" delay={800} />
          </span>
        </h1>
        <RevealWrapper delay={1200} direction="up">
          <p className="text-gray-400 text-sm md:text-base font-medium max-w-2xl mx-auto leading-relaxed mb-6">
            Initialize a direct briefing with Lead Engineer Rudi Mouton. Discuss custom network deployments, hardware architecture, or deep-level system diagnostics.
          </p>
          <div className="flex items-center justify-center gap-2 text-xs font-mono text-gray-500 uppercase tracking-widest">
            <ShieldCheck className="w-3.5 h-3.5 text-blue-400" />
            <span>Consultation parameters establish dynamic project scope</span>
          </div>
        </RevealWrapper>
      </header>

      {/* --------------------------------------------------------- */}
      {/* MAIN SPLIT LAYOUT */}
      {/* --------------------------------------------------------- */}
      <div className="w-full max-w-6xl grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 mb-24">
        
        {/* LEFT COLUMN: PROTOCOL INFO */}
        <div className="lg:col-span-5 flex flex-col gap-6">
          <RevealWrapper delay={400} direction="right" className="h-full">
            <div className="glass-card h-full rounded-[2.5rem] p-8 md:p-10 border border-white/5 bg-gradient-to-br from-white/[0.03] to-transparent relative overflow-hidden flex flex-col">
              <div className="absolute top-0 right-0 w-64 h-64 bg-indigo-600/10 rounded-full blur-[80px] pointer-events-none" />
              
              <div className="w-16 h-16 rounded-2xl bg-indigo-500/10 flex items-center justify-center border border-indigo-500/20 mb-8 relative z-10 shrink-0">
                <Network className="w-8 h-8 text-indigo-400" />
              </div>
              
              <h2 className="text-2xl font-black text-white uppercase tracking-wider mb-8 relative z-10">
                Briefing <br /> Parameters
              </h2>
              
              <div className="flex flex-col gap-8 flex-grow relative z-10">
                <div className="flex items-start gap-5">
                  <div className="w-10 h-10 rounded-xl bg-black/50 border border-white/10 flex items-center justify-center shrink-0">
                    <Video className="w-4 h-4 text-indigo-400" />
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-1">Encrypted Comms</h4>
                    <p className="text-xs font-mono text-gray-500 leading-relaxed">Consultations are conducted via secure Google Meet or Microsoft Teams links.</p>
                  </div>
                </div>

                <div className="flex items-start gap-5">
                  <div className="w-10 h-10 rounded-xl bg-black/50 border border-white/10 flex items-center justify-center shrink-0">
                    <Clock className="w-4 h-4 text-blue-400" />
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-1">Time Zone Sync</h4>
                    <p className="text-xs font-mono text-gray-500 leading-relaxed">All requested times are processed in South African Standard Time (SAST).</p>
                  </div>
                </div>

                <div className="flex items-start gap-5">
                  <div className="w-10 h-10 rounded-xl bg-black/50 border border-white/10 flex items-center justify-center shrink-0">
                    <Terminal className="w-4 h-4 text-emerald-400" />
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-1">Architectural Scope</h4>
                    <p className="text-xs font-mono text-gray-500 leading-relaxed">Be prepared to supply exact technical specifications and operational requirements.</p>
                  </div>
                </div>
              </div>
            </div>
          </RevealWrapper>
        </div>

        {/* RIGHT COLUMN: THE SCHEDULING ENGINE */}
        <div className="lg:col-span-7">
          <RevealWrapper delay={600} direction="up" className="h-full">
            <div className="glass-card rounded-[2.5rem] p-8 md:p-12 border border-blue-500/20 bg-[#080808] shadow-[0_0_80px_rgba(59,130,246,0.05)] relative overflow-hidden h-full flex flex-col">
              <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-blue-600/5 rounded-full blur-[100px] pointer-events-none" />
              
              <form id="scheduleForm" onSubmit={handleScheduleSubmit} className="space-y-8 relative z-10 flex flex-col flex-grow">
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Client Authorization</label>
                    <input 
                      type="text" 
                      required 
                      placeholder="Full Name / Org" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={scheduleForm.name} 
                      onChange={(e) => setScheduleForm({...scheduleForm, name: e.target.value})} 
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Secure Email</label>
                    <input 
                      type="email" 
                      required 
                      placeholder="your.email@example.com" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={scheduleForm.email} 
                      onChange={(e) => setScheduleForm({...scheduleForm, email: e.target.value})} 
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 bg-white/5 p-6 rounded-3xl border border-white/5">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Target Date</label>
                    <input 
                      type="date" 
                      required
                      min={minDate}
                      className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base cursor-pointer [color-scheme:dark]" 
                      value={scheduleForm.date} 
                      onChange={(e) => setScheduleForm({...scheduleForm, date: e.target.value})} 
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Time Block (SAST)</label>
                    <select 
                      className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base cursor-pointer appearance-none" 
                      value={scheduleForm.time} 
                      onChange={(e) => setScheduleForm({...scheduleForm, time: e.target.value})}
                    >
                      <option>09:00 AM</option>
                      <option>11:00 AM</option>
                      <option>01:00 PM</option>
                      <option>03:00 PM</option>
                      <option>05:00 PM</option>
                    </select>
                  </div>
                </div>

                <div className="space-y-3 flex-grow flex flex-col">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Consultation Topic & Briefing</label>
                  <textarea 
                    required 
                    placeholder="Provide a brief overview of the architecture, sourcing requirements, or systems you wish to discuss..." 
                    className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base resize-none placeholder:text-gray-600 shadow-inner flex-grow custom-scrollbar min-h-[120px]" 
                    value={scheduleForm.notes} 
                    onChange={(e) => setScheduleForm({...scheduleForm, notes: e.target.value})} 
                  />
                </div>

                <div className="pt-4 mt-auto">
                  <MagneticWrapper pullStrength={0.1}>
                    <button 
                      form="scheduleForm" 
                      type="submit" 
                      disabled={isSubmitting} 
                      className="w-full py-6 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-900/50 disabled:text-blue-400/50 disabled:cursor-not-allowed rounded-2xl font-black text-sm md:text-base uppercase tracking-widest flex justify-center items-center gap-4 transition-all shadow-[0_10px_40px_rgba(59,130,246,0.3)] hover:shadow-[0_15px_50px_rgba(59,130,246,0.5)] hover:-translate-y-1 ring-1 ring-blue-400/50 min-h-[72px]"
                    >
                      {isSubmitting ? (
                        <><Loader2 className="w-6 h-6 animate-spin" /> Securing Time Vector...</>
                      ) : (
                        <>Initialize Briefing Protocol <ArrowRight className="w-5 h-5" /></>
                      )}
                    </button>
                  </MagneticWrapper>
                </div>
              </form>
            </div>
          </RevealWrapper>
        </div>

      </div>
    </div>
  );
}

export default function SchedulePage() {
  return (
    <main className="min-h-[100svh] pt-24 pb-20 px-4 md:px-6 flex flex-col items-center overflow-hidden relative w-full">
      {/* Global Background Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-6xl h-[600px] bg-indigo-600/5 rounded-[100%] blur-[150px] pointer-events-none z-0" aria-hidden="true" />
      <div className="scanline opacity-10 pointer-events-none absolute inset-0 z-0" aria-hidden="true" />
      
      <Suspense fallback={<div className="min-h-screen flex items-center justify-center w-full"><Loader2 className="w-10 h-10 text-indigo-500 animate-spin" /></div>}>
        <ScheduleLogic />
      </Suspense>
    </main>
  );
}