"use client";
import { useState, Suspense } from "react";
import { useRouter } from "next/navigation";
import { Calendar, Clock, MapPin, Loader2, ArrowRight, Video, CalendarDays, Server, ShieldCheck } from "lucide-react";
import DecodeText from "../components/DecodeText";
import RevealWrapper from "../components/RevealWrapper";
import MagneticWrapper from "../components/MagneticWrapper";

const TIME_SLOTS = [
  "09:00 AM", "10:00 AM", "11:30 AM", 
  "01:00 PM", "02:30 PM", "04:00 PM"
];

const CONSULT_TYPES = [
  { id: "virtual", label: "Virtual Consultation", icon: <Video className="w-5 h-5" />, desc: "Remote system architecture review." },
  { id: "onsite", label: "On-Site Deployment", icon: <Server className="w-5 h-5" />, desc: "Physical hardware or network installation." },
];

function ScheduleLogic() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [selectedDate, setSelectedDate] = useState<string>("");
  const [selectedTime, setSelectedTime] = useState<string>("");
  const [selectedType, setSelectedType] = useState<string>("virtual");
  
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    company: "",
    details: "",
  });

  // Calculate next 14 available business days
  const getAvailableDates = () => {
    const dates = [];
    const today = new Date();
    let count = 0;
    let current = new Date(today);
    
    // Start from tomorrow
    current.setDate(current.getDate() + 1);

    while (count < 14) {
      const day = current.getDay();
      // Skip weekends (0 = Sunday, 6 = Saturday)
      if (day !== 0 && day !== 6) {
        dates.push(new Date(current));
        count++;
      }
      current.setDate(current.getDate() + 1);
    }
    return dates;
  };

  const availableDates = getAvailableDates();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!selectedDate || !selectedTime) {
      alert("Please select both a date and a time slot.");
      return;
    }
    
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
CONSULTATION SCHEDULED
=========================================
CLIENT INFORMATION
-----------------------------------------
Name:     ${formData.name}
Email:    ${formData.email}
Company:  ${formData.company || 'Not Provided'}

MEETING PARAMETERS
-----------------------------------------
Type:     ${selectedType === 'virtual' ? 'Virtual Consultation' : 'On-Site Deployment'}
Date:     ${new Date(selectedDate).toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}
Time:     ${selectedTime} (SAST)

PROJECT DETAILS
-----------------------------------------
${formData.details || "No details provided."}
=========================================
System Generated by The Mouton Hub
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", formData.name || "Hub Client");
      payload.append("email", formData.email || "no-reply@themoutonhub.com");
      payload.append("subject", `Meeting Request: ${formData.name} - ${selectedDate}`);
      payload.append("from_name", "The Mouton Hub Scheduling");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: payload });
      const result = await response.json();
      
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to transmit request. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="w-full flex flex-col items-center relative z-10 px-4 md:px-6">
      
      {/* --------------------------------------------------------- */}
      {/* HEADER */}
      {/* --------------------------------------------------------- */}
      <header className="w-full max-w-5xl mb-16 text-center mt-10">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 mb-6 backdrop-blur-md">
          <CalendarDays className="w-4 h-4 text-blue-400" />
          <span className="text-xs font-mono text-blue-300 uppercase tracking-widest">Scheduling Engine Active</span>
        </div>
        <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase mb-6 leading-none">
          <DecodeText text="Operational" /> <br />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-cyan-400 drop-shadow-[0_0_30px_rgba(0,163,255,0.3)]">
            <DecodeText text="Scheduling" delay={600} />
          </span>
        </h1>
        <RevealWrapper delay={1000} direction="up">
          <p className="text-gray-400 text-sm md:text-base font-medium max-w-2xl mx-auto leading-relaxed">
            Reserve a dedicated time slot for high-level system architecture planning, hardware deployment strategy, or intensive diagnostic review.
          </p>
        </RevealWrapper>
      </header>

      {/* --------------------------------------------------------- */}
      {/* MAIN SCHEDULING INTERFACE */}
      {/* --------------------------------------------------------- */}
      <div className="w-full max-w-6xl grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 mb-20">
        
        {/* LEFT COLUMN: DATE & TIME SELECTION */}
        <div className="lg:col-span-5 flex flex-col gap-8">
          <RevealWrapper delay={200} direction="right" className="h-full">
            <div className="glass-card h-full rounded-[2.5rem] p-8 md:p-10 border border-white/5 bg-gradient-to-b from-white/[0.03] to-transparent relative overflow-hidden flex flex-col">
              <div className="absolute top-0 right-0 w-64 h-64 bg-blue-600/10 rounded-full blur-[80px] pointer-events-none" />
              
              <h2 className="text-2xl font-black text-white uppercase tracking-wider mb-8 relative z-10 flex items-center gap-3">
                <Calendar className="w-6 h-6 text-blue-400" /> Time Vector
              </h2>
              
              {/* Date Selection */}
              <div className="mb-8 relative z-10">
                <label className="text-xs font-mono text-gray-400 uppercase tracking-widest block mb-4">1. Select Available Date</label>
                <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-2 xl:grid-cols-3 gap-3">
                  {availableDates.slice(0, 6).map((date, index) => {
                    const dateStr = date.toISOString();
                    const isSelected = selectedDate === dateStr;
                    return (
                      <button
                        key={index}
                        onClick={() => setSelectedDate(dateStr)}
                        className={`flex flex-col items-center justify-center p-3 rounded-2xl border transition-all duration-300 ${
                          isSelected 
                            ? "bg-blue-600 border-blue-500 shadow-[0_0_20px_rgba(37,99,235,0.4)]" 
                            : "bg-[#111] hover:bg-[#1a1a1a] border-white/10 hover:border-blue-500/30"
                        }`}
                      >
                        <span className={`text-[10px] font-mono uppercase tracking-widest ${isSelected ? "text-blue-100" : "text-gray-500"}`}>
                          {date.toLocaleDateString('en-US', { weekday: 'short' })}
                        </span>
                        <span className={`text-xl font-black ${isSelected ? "text-white" : "text-gray-300"}`}>
                          {date.getDate()}
                        </span>
                        <span className={`text-[10px] font-mono uppercase tracking-widest ${isSelected ? "text-blue-100" : "text-gray-500"}`}>
                          {date.toLocaleDateString('en-US', { month: 'short' })}
                        </span>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Time Selection */}
              <div className="relative z-10">
                <label className="text-xs font-mono text-gray-400 uppercase tracking-widest block mb-4">2. Select Time Slot (SAST)</label>
                <div className="grid grid-cols-2 gap-3">
                  {TIME_SLOTS.map((time, index) => {
                    const isSelected = selectedTime === time;
                    return (
                      <button
                        key={index}
                        onClick={() => setSelectedTime(time)}
                        className={`flex items-center justify-center gap-2 p-4 rounded-xl border transition-all duration-300 font-mono text-sm tracking-wider ${
                          isSelected 
                            ? "bg-blue-600 border-blue-500 text-white shadow-[0_0_20px_rgba(37,99,235,0.4)]" 
                            : "bg-[#111] hover:bg-[#1a1a1a] border-white/10 hover:border-blue-500/30 text-gray-400"
                        }`}
                      >
                        <Clock className={`w-4 h-4 ${isSelected ? "text-white" : "text-gray-500"}`} /> {time}
                      </button>
                    );
                  })}
                </div>
              </div>

            </div>
          </RevealWrapper>
        </div>

        {/* RIGHT COLUMN: CLIENT DETAILS FORM */}
        <div className="lg:col-span-7">
          <RevealWrapper delay={400} direction="up" className="h-full">
            <div className="glass-card rounded-[2.5rem] p-8 md:p-12 border border-blue-500/20 bg-[#080808] shadow-[0_0_80px_rgba(0,163,255,0.05)] relative overflow-hidden h-full flex flex-col">
              <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-blue-600/5 rounded-full blur-[100px] pointer-events-none" />
              
              <form id="scheduleForm" onSubmit={handleSubmit} className="space-y-8 relative z-10 flex flex-col flex-grow">
                
                {/* Consultation Type Toggle */}
                <div className="space-y-3">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">3. Protocol Type</label>
                  <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                    {CONSULT_TYPES.map((type) => {
                      const isSelected = selectedType === type.id;
                      return (
                        <div 
                          key={type.id}
                          onClick={() => setSelectedType(type.id)}
                          className={`cursor-pointer p-5 rounded-2xl border transition-all duration-300 flex items-start gap-4 ${
                            isSelected 
                              ? "bg-blue-900/20 border-blue-500/50" 
                              : "bg-[#111] border-white/10 hover:border-white/20"
                          }`}
                        >
                          <div className={`mt-0.5 shrink-0 ${isSelected ? "text-blue-400" : "text-gray-500"}`}>
                            {type.icon}
                          </div>
                          <div>
                            <h4 className={`text-sm font-black uppercase tracking-wider mb-1 ${isSelected ? "text-white" : "text-gray-300"}`}>
                              {type.label}
                            </h4>
                            <p className="text-xs font-mono text-gray-500 leading-relaxed">{type.desc}</p>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>

                {/* Client Details */}
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Client Name</label>
                    <input 
                      type="text" 
                      required 
                      placeholder="Full Name" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={formData.name} 
                      onChange={(e) => setFormData({...formData, name: e.target.value})} 
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Email Address</label>
                    <input 
                      type="email" 
                      required 
                      placeholder="your.email@example.com" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={formData.email} 
                      onChange={(e) => setFormData({...formData, email: e.target.value})} 
                    />
                  </div>
                </div>

                <div className="space-y-3">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Company / Organization (Optional)</label>
                  <input 
                    type="text" 
                    placeholder="Enter Organization Name" 
                    className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                    value={formData.company} 
                    onChange={(e) => setFormData({...formData, company: e.target.value})} 
                  />
                </div>

                <div className="space-y-3 flex-grow flex flex-col">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Project Scope / Agenda</label>
                  <textarea 
                    required 
                    placeholder="Briefly describe the hardware requirements or diagnostic focus for this meeting..." 
                    className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base resize-none placeholder:text-gray-600 shadow-inner flex-grow custom-scrollbar min-h-[120px]" 
                    value={formData.details} 
                    onChange={(e) => setFormData({...formData, details: e.target.value})} 
                  />
                </div>

                <div className="pt-4 mt-auto">
                  <MagneticWrapper pullStrength={0.1}>
                    <button 
                      form="scheduleForm" 
                      type="submit" 
                      disabled={isSubmitting} 
                      className="w-full py-6 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-900/50 disabled:text-blue-400/50 disabled:cursor-not-allowed rounded-2xl font-black text-sm md:text-base uppercase tracking-widest flex justify-center items-center gap-4 transition-all shadow-[0_10px_40px_rgba(37,99,235,0.3)] hover:shadow-[0_15px_50px_rgba(37,99,235,0.5)] hover:-translate-y-1 ring-1 ring-blue-400/50 min-h-[72px]"
                    >
                      {isSubmitting ? (
                        <><Loader2 className="w-6 h-6 animate-spin" /> Locking Parameters...</>
                      ) : (
                        <>Confirm Time Vector <ArrowRight className="w-5 h-5" /></>
                      )}
                    </button>
                  </MagneticWrapper>
                </div>
              </form>
            </div>
          </RevealWrapper>
        </div>
      </div>
    </div>
  );
}

export default function SchedulePage() {
  return (
    <main className="min-h-screen pt-24 pb-20 flex flex-col items-center overflow-hidden relative w-full">
      {/* Global Background Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-6xl h-[600px] bg-blue-600/5 rounded-[100%] blur-[150px] pointer-events-none z-0" aria-hidden="true" />
      <div className="scanline opacity-10 pointer-events-none absolute inset-0 z-0" aria-hidden="true" />
      
      <Suspense fallback={<div className="min-h-screen flex items-center justify-center w-full"><Loader2 className="w-10 h-10 text-blue-500 animate-spin" /></div>}>
        <ScheduleLogic />
      </Suspense>
    </main>
  );
}