"use client";
import { useState, Suspense } from "react";
import { useRouter } from "next/navigation";
import { Terminal, Send, Loader2, Mail, MapPin, Clock, ShieldAlert, Cpu } from "lucide-react";
import DecodeText from "../components/DecodeText";
import RevealWrapper from "../components/RevealWrapper";
import MagneticWrapper from "../components/MagneticWrapper";

function ContactLogic() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    subject: "System Diagnostics",
    message: "",
    priority: "Standard",
  });

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
TAKUMI TECH - DIAGNOSTIC TICKET
=========================================
CLIENT INFORMATION
-----------------------------------------
Name:     ${formData.name}
Email:    ${formData.email}

TICKET PARAMETERS
-----------------------------------------
Category: ${formData.subject}
Priority: ${formData.priority.toUpperCase()}

SYSTEM DIAGNOSTIC LOG / MESSAGE
-----------------------------------------
${formData.message}
=========================================
System Generated by Takumitech.co.za
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", formData.name || "Takumi Client");
      payload.append("email", formData.email || "no-reply@takumitech.co.za");
      payload.append("subject", `[${formData.priority.toUpperCase()}] ${formData.subject} - ${formData.name}`);
      payload.append("from_name", "Takumi Tech Support");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: payload });
      const result = await response.json();
      
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to transmit request. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="w-full flex flex-col items-center relative z-10 px-4 md:px-6">
      
      {/* --------------------------------------------------------- */}
      {/* HEADER */}
      {/* --------------------------------------------------------- */}
      <header className="w-full max-w-6xl mb-16 text-center lg:text-left flex flex-col lg:flex-row items-center justify-between gap-8 mt-10">
        <div>
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-blue-500/10 border border-blue-500/20 mb-6 backdrop-blur-md">
            <ShieldAlert className="w-4 h-4 text-blue-400" />
            <span className="text-xs font-mono text-blue-300 uppercase tracking-widest">Secure Comms Channel Open</span>
          </div>
          <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase mb-4 leading-none">
            <DecodeText text="Diagnostic" /> <br />
            <span className="text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-cyan-400 drop-shadow-[0_0_30px_rgba(0,163,255,0.3)]">
              <DecodeText text="Ticketing" delay={500} />
            </span>
          </h1>
          <RevealWrapper delay={1000} direction="up">
            <p className="text-gray-400 text-sm md:text-base font-medium max-w-xl leading-relaxed">
              Initialize a secure support ticket. Takumi Tech engineers will intercept and review your request within operational hours.
            </p>
          </RevealWrapper>
        </div>

        {/* Floating Telemetry Box (Desktop Only) */}
        <div className="hidden lg:flex glass-card rounded-[2rem] p-6 border border-white/5 bg-[#111]/50 backdrop-blur-md items-center gap-6">
          <div className="w-16 h-16 rounded-2xl bg-blue-500/10 flex items-center justify-center border border-blue-500/20">
            <Terminal className="w-8 h-8 text-blue-400" />
          </div>
          <div>
            <h3 className="text-white font-black uppercase tracking-wider mb-1">Takumi Node</h3>
            <p className="text-xs font-mono text-gray-400 uppercase tracking-widest">Routing via Cape Town, ZA</p>
          </div>
        </div>
      </header>

      {/* --------------------------------------------------------- */}
      {/* MAIN SPLIT LAYOUT */}
      {/* --------------------------------------------------------- */}
      <div className="w-full max-w-6xl grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 mb-20">
        
        {/* LEFT COLUMN: CONTACT INFO */}
        <div className="lg:col-span-5 flex flex-col gap-6">
          <RevealWrapper delay={200} direction="right" className="h-full flex flex-col">
            <div className="glass-card h-full flex-grow rounded-[2.5rem] p-8 md:p-10 border border-white/5 bg-gradient-to-b from-white/[0.03] to-transparent relative overflow-hidden flex flex-col">
              <div className="absolute top-0 right-0 w-64 h-64 bg-blue-600/10 rounded-full blur-[80px] pointer-events-none" />
              
              <h2 className="text-2xl font-black text-white uppercase tracking-wider mb-8 relative z-10">Operational Data</h2>
              
              <div className="flex flex-col gap-8 flex-grow relative z-10">
                {/* Email Node */}
                <div className="flex items-start gap-5 group">
                  <div className="w-12 h-12 rounded-xl bg-black/50 border border-white/10 flex items-center justify-center group-hover:border-blue-500/50 group-hover:bg-blue-500/10 transition-all shrink-0">
                    <Mail className="w-5 h-5 text-gray-400 group-hover:text-blue-400 transition-colors" />
                  </div>
                  <div>
                    <h4 className="text-[10px] font-mono text-gray-500 uppercase tracking-widest mb-1">Direct Encrypted Route</h4>
                    <a href="mailto:systems@takumitech.co.za" className="text-base font-bold text-white hover:text-blue-400 transition-colors">
                      systems@takumitech.co.za
                    </a>
                  </div>
                </div>

                {/* Location Node */}
                <div className="flex items-start gap-5 group">
                  <div className="w-12 h-12 rounded-xl bg-black/50 border border-white/10 flex items-center justify-center group-hover:border-emerald-500/50 group-hover:bg-emerald-500/10 transition-all shrink-0">
                    <MapPin className="w-5 h-5 text-gray-400 group-hover:text-emerald-400 transition-colors" />
                  </div>
                  <div>
                    <h4 className="text-[10px] font-mono text-gray-500 uppercase tracking-widest mb-1">Primary Base</h4>
                    <p className="text-base font-bold text-white">
                      Oakdale, Bellville<br />Cape Town, South Africa
                    </p>
                  </div>
                </div>

                {/* Hours Node */}
                <div className="flex items-start gap-5 group">
                  <div className="w-12 h-12 rounded-xl bg-black/50 border border-white/10 flex items-center justify-center group-hover:border-cyan-500/50 group-hover:bg-cyan-500/10 transition-all shrink-0">
                    <Clock className="w-5 h-5 text-gray-400 group-hover:text-cyan-400 transition-colors" />
                  </div>
                  <div>
                    <h4 className="text-[10px] font-mono text-gray-500 uppercase tracking-widest mb-1">System Uptime</h4>
                    <p className="text-base font-bold text-white">
                      Mon-Fri: 08:00 - 18:00<br />Sat: Standby Mode
                    </p>
                  </div>
                </div>
              </div>

              {/* Secure Warning Box */}
              <div className="mt-10 p-5 rounded-2xl bg-blue-900/10 border border-blue-500/20 flex items-start gap-4 relative z-10">
                <Cpu className="w-5 h-5 text-blue-400 shrink-0 mt-0.5" />
                <p className="text-xs font-mono text-blue-200 leading-relaxed uppercase tracking-wide">
                  Transmission Protocol: Active. All data payloads are secured and directly routed to Takumi Tech infrastructure.
                </p>
              </div>

            </div>
          </RevealWrapper>
        </div>

        {/* RIGHT COLUMN: THE FORM */}
        <div className="lg:col-span-7 flex flex-col">
          <RevealWrapper delay={400} direction="up" className="h-full flex flex-col">
            <div className="glass-card flex-grow rounded-[2.5rem] p-8 md:p-12 border border-blue-500/20 bg-[#080808] shadow-[0_0_80px_rgba(0,163,255,0.05)] relative overflow-hidden flex flex-col">
              <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-blue-600/5 rounded-full blur-[100px] pointer-events-none" />
              
              <form id="contactForm" onSubmit={handleSubmit} className="space-y-8 relative z-10 flex flex-col flex-grow">
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Client Name / ID</label>
                    <input 
                      type="text" 
                      required 
                      placeholder="Enter Full Name" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={formData.name} 
                      onChange={(e) => setFormData({...formData, name: e.target.value})} 
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Return Email</label>
                    <input 
                      type="email" 
                      required 
                      placeholder="your.email@example.com" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={formData.email} 
                      onChange={(e) => setFormData({...formData, email: e.target.value})} 
                    />
                  </div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 bg-white/5 p-6 rounded-3xl border border-white/5">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Ticket Category</label>
                    <select 
                      className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base cursor-pointer appearance-none" 
                      value={formData.subject} 
                      onChange={(e) => setFormData({...formData, subject: e.target.value})}
                    >
                      <option>System Diagnostics</option>
                      <option>Network Architecture</option>
                      <option>Hardware Sourcing Support</option>
                      <option>General Inquiry</option>
                    </select>
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Priority Level</label>
                    <select 
                      className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base cursor-pointer appearance-none" 
                      value={formData.priority} 
                      onChange={(e) => setFormData({...formData, priority: e.target.value})}
                    >
                      <option>Standard (48h Response)</option>
                      <option>Elevated (24h Response)</option>
                      <option>Critical (Immediate)</option>
                    </select>
                  </div>
                </div>

                <div className="space-y-3 flex-grow flex flex-col">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Diagnostic Log / Message</label>
                  <textarea 
                    required 
                    placeholder="Describe the system anomaly, architectural scope, or sourcing requirements in detail..." 
                    className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500 transition-all text-base resize-none placeholder:text-gray-600 shadow-inner flex-grow custom-scrollbar min-h-[120px]" 
                    value={formData.message} 
                    onChange={(e) => setFormData({...formData, message: e.target.value})} 
                  />
                </div>

                <div className="pt-4 mt-auto">
                  <MagneticWrapper pullStrength={0.1}>
                    <button 
                      form="contactForm" 
                      type="submit" 
                      disabled={isSubmitting} 
                      className="w-full py-6 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-900/50 disabled:text-blue-400/50 disabled:cursor-not-allowed rounded-2xl font-black text-sm md:text-base uppercase tracking-widest flex justify-center items-center gap-4 transition-all shadow-[0_10px_40px_rgba(37,99,235,0.3)] hover:shadow-[0_15px_50px_rgba(37,99,235,0.5)] hover:-translate-y-1 ring-1 ring-blue-400/50 min-h-[72px]"
                    >
                      {isSubmitting ? (
                        <><Loader2 className="w-6 h-6 animate-spin" /> Encrypting & Transmitting...</>
                      ) : (
                        <>Transmit Ticket Payload <Send className="w-5 h-5" /></>
                      )}
                    </button>
                  </MagneticWrapper>
                </div>
              </form>
            </div>
          </RevealWrapper>
        </div>
      </div>
    </div>
  );
}

export default function ContactPage() {
  return (
    <main className="min-h-[100svh] pt-24 pb-20 flex flex-col items-center overflow-hidden relative w-full">
      {/* Global Background Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-6xl h-[600px] bg-blue-600/5 rounded-[100%] blur-[150px] pointer-events-none z-0" aria-hidden="true" />
      <div className="scanline opacity-10 pointer-events-none absolute inset-0 z-0" aria-hidden="true" />
      
      <Suspense fallback={<div className="min-h-screen flex items-center justify-center w-full"><Loader2 className="w-10 h-10 text-blue-500 animate-spin" /></div>}>
        <ContactLogic />
      </Suspense>
    </main>
  );
}