"use client";
import { useState, Suspense } from "react";
import { useRouter } from "next/navigation";
import { Search, Loader2, ArrowRight, ShieldCheck, Globe, Cpu } from "lucide-react";
import DecodeText from "../components/DecodeText";
import MagneticWrapper from "../components/MagneticWrapper";
import RevealWrapper from "../components/RevealWrapper";

function SourcingLogic() {
  const router = useRouter();
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [sourcingForm, setSourcingForm] = useState({ 
    name: "", 
    email: "", 
    specs: "", 
    useCase: "Enterprise Deployment", 
    condition: "Brand New Only" 
  });

  const handleSourcingSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
TAKUMI TECH - CUSTOM SOURCING REQUEST
=========================================
CLIENT INFORMATION
-----------------------------------------
Name:         ${sourcingForm.name}
Email:        ${sourcingForm.email}

SOURCING PARAMETERS
-----------------------------------------
Use Case:     ${sourcingForm.useCase}
Condition:    ${sourcingForm.condition}

PART SPECIFICATIONS / ARCHITECTURE NEEDS
-----------------------------------------
${sourcingForm.specs}
=========================================
System Generated by Takumitech.co.za
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", sourcingForm.name || "Takumi Client");
      payload.append("email", sourcingForm.email || "no-reply@takumitech.co.za");
      payload.append("subject", `Sourcing Protocol: ${sourcingForm.name}`);
      payload.append("from_name", "Takumi Tech Sourcing");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: payload });
      const result = await response.json();
      
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to transmit request. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <div className="w-full flex flex-col items-center relative z-10 px-4 md:px-6">
      
      {/* --------------------------------------------------------- */}
      {/* HEADER SECTION */}
      {/* --------------------------------------------------------- */}
      <header className="w-full max-w-5xl mb-16 text-center relative z-10 mx-auto mt-10">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-6 backdrop-blur-md">
          <Globe className="w-4 h-4 text-emerald-400 animate-pulse" />
          <span className="text-xs font-mono text-emerald-300 uppercase tracking-widest">Global Logistics Network</span>
        </div>
        <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase mb-6 leading-none">
          <DecodeText text="Hardware" /> <br className="md:hidden" />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400 drop-shadow-[0_0_30px_rgba(16,185,129,0.3)]">
            <DecodeText text="Sourcing" delay={800} />
          </span>
        </h1>
        <RevealWrapper delay={1200} direction="up">
          <p className="text-gray-400 text-sm md:text-base font-medium max-w-2xl mx-auto leading-relaxed mb-6">
            Direct access to rare, enterprise-grade computational components. We bypass standard retail limitations to acquire specialized technology directly from global distribution channels.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-3 text-xs font-mono text-emerald-400 uppercase tracking-widest bg-emerald-500/5 p-4 rounded-xl border border-emerald-500/20 max-w-3xl mx-auto">
            <ShieldCheck className="w-5 h-5 shrink-0" />
            <span className="text-center sm:text-left leading-relaxed">
              <strong>Dynamic Pricing Protocol:</strong> Hardware costs vary per individual client case due to fluctuating global supply chains, import tariffs, and exact specification requirements.
            </span>
          </div>
        </RevealWrapper>
      </header>

      {/* --------------------------------------------------------- */}
      {/* INTEGRATED SOURCING FORM */}
      {/* --------------------------------------------------------- */}
      <div className="w-full max-w-5xl grid grid-cols-1 lg:grid-cols-12 gap-8 lg:gap-12 mb-24">
        
        {/* LEFT COLUMN: THE PROCESS */}
        <div className="lg:col-span-5 flex flex-col gap-6">
          <RevealWrapper delay={400} direction="right" className="h-full">
            <div className="glass-card h-full rounded-[2.5rem] p-8 md:p-10 border border-white/5 bg-gradient-to-b from-white/[0.03] to-transparent relative overflow-hidden flex flex-col">
              <div className="absolute top-0 right-0 w-64 h-64 bg-emerald-600/10 rounded-full blur-[80px] pointer-events-none" />
              
              <div className="w-16 h-16 rounded-2xl bg-emerald-500/10 flex items-center justify-center border border-emerald-500/20 mb-8 relative z-10 shrink-0">
                <Cpu className="w-8 h-8 text-emerald-400" />
              </div>
              
              <h2 className="text-2xl font-black text-white uppercase tracking-wider mb-8 relative z-10">
                Acquisition <br /> Protocol
              </h2>
              
              <div className="flex flex-col gap-8 flex-grow relative z-10">
                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 rounded-full bg-[#111] border border-white/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs font-black text-emerald-400">1</span>
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-1">Submit Specifications</h4>
                    <p className="text-xs font-mono text-gray-500 leading-relaxed">Provide the exact model numbers, performance requirements, and condition criteria.</p>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 rounded-full bg-[#111] border border-white/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs font-black text-emerald-400">2</span>
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-1">Market Analysis</h4>
                    <p className="text-xs font-mono text-gray-500 leading-relaxed">Our engineers query global distribution nodes to secure the most efficient procurement route.</p>
                  </div>
                </div>

                <div className="flex items-start gap-4">
                  <div className="w-8 h-8 rounded-full bg-[#111] border border-white/10 flex items-center justify-center shrink-0 mt-0.5">
                    <span className="text-xs font-black text-emerald-400">3</span>
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white uppercase tracking-wider mb-1">Custom Assessment</h4>
                    <p className="text-xs font-mono text-gray-500 leading-relaxed">You receive a tailored breakdown of dynamic costs and logistics ETAs for your specific case.</p>
                  </div>
                </div>
              </div>
            </div>
          </RevealWrapper>
        </div>

        {/* RIGHT COLUMN: THE SOURCING ENGINE */}
        <div className="lg:col-span-7">
          <RevealWrapper delay={600} direction="up" className="h-full">
            <div className="glass-card rounded-[2.5rem] p-8 md:p-12 border border-emerald-500/20 bg-[#080808] shadow-[0_0_80px_rgba(16,185,129,0.05)] relative overflow-hidden h-full flex flex-col">
              <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-emerald-600/5 rounded-full blur-[100px] pointer-events-none" />
              
              <form id="sourcingForm" onSubmit={handleSourcingSubmit} className="space-y-8 relative z-10 flex flex-col flex-grow">
                
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Client Name</label>
                    <input 
                      type="text" 
                      required 
                      placeholder="Full Name" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={sourcingForm.name} 
                      onChange={(e) => setSourcingForm({...sourcingForm, name: e.target.value})} 
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Secure Email</label>
                    <input 
                      type="email" 
                      required 
                      placeholder="your.email@example.com" 
                      className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 transition-all text-base placeholder:text-gray-600 shadow-inner" 
                      value={sourcingForm.email} 
                      onChange={(e) => setSourcingForm({...sourcingForm, email: e.target.value})} 
                    />
                  </div>
                </div>

                <div className="space-y-3 flex-grow flex flex-col">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Exact Part Specifications & Needs</label>
                  <textarea 
                    required 
                    placeholder="E.g. Intel Core i9-14900K, custom server racks, or full system architecture builds..." 
                    className="w-full bg-[#111] hover:bg-[#1a1a1a] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 transition-all text-base resize-none placeholder:text-gray-600 shadow-inner flex-grow custom-scrollbar min-h-[140px]" 
                    value={sourcingForm.specs} 
                    onChange={(e) => setSourcingForm({...sourcingForm, specs: e.target.value})} 
                  />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 bg-white/5 p-6 rounded-3xl border border-white/5">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Deployment Scale</label>
                    <select 
                      className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 transition-all text-base cursor-pointer appearance-none" 
                      value={sourcingForm.useCase} 
                      onChange={(e) => setSourcingForm({...sourcingForm, useCase: e.target.value})}
                    >
                      <option>Enterprise Deployment</option>
                      <option>Professional Workstation</option>
                      <option>Enthusiast / Gaming Node</option>
                      <option>Network Infrastructure</option>
                    </select>
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Hardware Condition</label>
                    <select 
                      className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/50 focus:border-emerald-500 transition-all text-base cursor-pointer appearance-none" 
                      value={sourcingForm.condition} 
                      onChange={(e) => setSourcingForm({...sourcingForm, condition: e.target.value})}
                    >
                      <option>Brand New Only</option>
                      <option>New or Certified Refurbished</option>
                      <option>Used / Second Hand Accepted</option>
                    </select>
                  </div>
                </div>

                <div className="pt-4 mt-auto">
                  <MagneticWrapper pullStrength={0.1}>
                    <button 
                      form="sourcingForm" 
                      type="submit" 
                      disabled={isSubmitting} 
                      className="w-full py-6 bg-emerald-600 hover:bg-emerald-500 disabled:bg-emerald-900/50 disabled:text-emerald-400/50 disabled:cursor-not-allowed rounded-2xl font-black text-sm md:text-base uppercase tracking-widest flex justify-center items-center gap-4 transition-all shadow-[0_10px_40px_rgba(16,185,129,0.3)] hover:shadow-[0_15px_50px_rgba(16,185,129,0.5)] hover:-translate-y-1 ring-1 ring-emerald-400/50 min-h-[72px]"
                    >
                      {isSubmitting ? (
                        <><Loader2 className="w-6 h-6 animate-spin" /> Transmitting Telemetry...</>
                      ) : (
                        <>Initialize Search Protocol <Search className="w-5 h-5" /></>
                      )}
                    </button>
                  </MagneticWrapper>
                </div>
              </form>
            </div>
          </RevealWrapper>
        </div>

      </div>
    </div>
  );
}

export default function ShopPage() {
  return (
    <main className="min-h-[100svh] pt-24 pb-20 px-4 md:px-6 flex flex-col items-center overflow-hidden relative w-full">
      {/* Global Background Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-6xl h-[600px] bg-emerald-600/5 rounded-[100%] blur-[150px] pointer-events-none z-0" aria-hidden="true" />
      <div className="scanline opacity-10 pointer-events-none absolute inset-0 z-0" aria-hidden="true" />
      
      <Suspense fallback={<div className="min-h-screen flex items-center justify-center w-full"><Loader2 className="w-10 h-10 text-emerald-500 animate-spin" /></div>}>
        <SourcingLogic />
      </Suspense>
    </main>
  );
}