"use client";
import { useState, Suspense } from "react";
import { useRouter } from "next/navigation";
import { Search, HardDrive, Cpu, Monitor, X, Loader2, ChevronRight, ArrowRight, ArrowLeft, Zap, ShieldCheck } from "lucide-react";
import DecodeText from "../components/DecodeText";
import MagneticWrapper from "../components/MagneticWrapper";
import RevealWrapper from "../components/RevealWrapper";

const HARDWARE_INVENTORY = [
  { id: 1, name: "Samsung 980 PRO 1TB NVMe", category: "High-Speed Storage", price: "R 2,499", icon: <HardDrive className="w-7 h-7" />, status: "In Stock" },
  { id: 2, name: "AMD Ryzen 7 5800X3D", category: "Processing Unit", price: "R 6,899", icon: <Cpu className="w-7 h-7" />, status: "Limited Supply" },
  { id: 3, name: "ASUS ROG Strix 27\" 1440p", category: "Tactical Display", price: "R 9,299", icon: <Monitor className="w-7 h-7" />, status: "In Stock" },
];

function ShopLogic() {
  const router = useRouter();
  
  const [activeInquiry, setActiveInquiry] = useState<typeof HARDWARE_INVENTORY[0] | null>(null);
  const [isSourcingModalOpen, setIsSourcingModalOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const [inquiryForm, setInquiryForm] = useState({ name: "", email: "", phone: "", message: "" });
  const [sourcingForm, setSourcingForm] = useState({ name: "", email: "", phone: "", specs: "", budget: "R1,000 - R3,000", condition: "Brand New Only" });

  const handleInquirySubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!activeInquiry) return;
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
HARDWARE INQUIRY LOGGED
=========================================
CLIENT INFORMATION
-----------------------------------------
Name:     ${inquiryForm.name}
Email:    ${inquiryForm.email}
Phone:    ${inquiryForm.phone || 'Not Provided'}

TARGET HARDWARE
-----------------------------------------
Product:  ${activeInquiry.name}
Category: ${activeInquiry.category}
Listed:   ${activeInquiry.price}

CLIENT MESSAGE
-----------------------------------------
${inquiryForm.message || "No additional questions."}
=========================================
System Generated by The Mouton Hub
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", inquiryForm.name || "Hub Client");
      payload.append("email", inquiryForm.email || "no-reply@themoutonhub.com");
      payload.append("subject", `Hardware Inquiry: ${activeInquiry.name} - ${inquiryForm.name}`);
      payload.append("from_name", "The Mouton Hub Store");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: payload });
      const result = await response.json();
      
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to transmit request. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleSourcingSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
CUSTOM SOURCING REQUEST
=========================================
CLIENT INFORMATION
-----------------------------------------
Name:     ${sourcingForm.name}
Email:    ${sourcingForm.email}
Phone:    ${sourcingForm.phone || 'Not Provided'}

SOURCING PARAMETERS
-----------------------------------------
Budget:       ${sourcingForm.budget}
Condition:    ${sourcingForm.condition}

PART SPECIFICATIONS
-----------------------------------------
${sourcingForm.specs}
=========================================
System Generated by The Mouton Hub
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", sourcingForm.name || "Hub Client");
      payload.append("email", sourcingForm.email || "no-reply@themoutonhub.com");
      payload.append("subject", `Custom Sourcing: ${sourcingForm.name}`);
      payload.append("from_name", "The Mouton Hub Sourcing");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", { method: "POST", body: payload });
      const result = await response.json();
      
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to transmit request. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      {/* HEADER SECTION */}
      <header className="w-full max-w-5xl mb-12 text-center relative z-10 mx-auto">
        <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-emerald-500/10 border border-emerald-500/20 mb-6 backdrop-blur-md">
          <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
          <span className="text-xs font-mono text-emerald-300 uppercase tracking-widest">Global Logistics Network Active</span>
        </div>
        <h1 className="text-5xl md:text-7xl font-black tracking-tighter uppercase mb-6 leading-none">
          <DecodeText text="Hardware" /> <br className="md:hidden" />
          <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400 drop-shadow-[0_0_30px_rgba(16,185,129,0.3)]">
            <DecodeText text="Procurement" delay={800} />
          </span>
        </h1>
        <RevealWrapper delay={1200} direction="up">
          <p className="text-gray-400 text-sm md:text-base font-medium max-w-2xl mx-auto leading-relaxed">
            Direct access to enterprise-grade components. Leverage our proprietary sourcing protocols to acquire rare, high-performance, and specialized technology.
          </p>
        </RevealWrapper>
      </header>

      {/* SWAPPED TO TOP: ULTRA-PREMIUM SOURCING BANNER */}
      <RevealWrapper delay={400} className="w-full max-w-5xl relative z-10 mb-24">
        <div className="glass-card rounded-[2.5rem] p-12 md:p-16 border border-emerald-500/30 bg-gradient-to-br from-emerald-900/20 to-black/60 shadow-[0_0_80px_rgba(16,185,129,0.1)] text-center relative overflow-hidden group hover:border-emerald-500/50 transition-colors duration-700">
          <div className="absolute inset-0 bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] opacity-5 mix-blend-overlay pointer-events-none" />
          <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-emerald-500/10 rounded-full blur-[100px] pointer-events-none group-hover:bg-emerald-500/20 transition-colors duration-1000" />
          
          <div className="relative z-10 flex flex-col items-center">
            <div className="w-24 h-24 rounded-3xl bg-black/60 backdrop-blur-xl flex items-center justify-center mb-8 border border-emerald-500/40 shadow-[0_0_40px_rgba(16,185,129,0.3)] group-hover:scale-110 group-hover:border-emerald-400 transition-all duration-700">
              <Search className="w-12 h-12 text-emerald-400 group-hover:animate-pulse" />
            </div>
            
            <h2 className="text-4xl md:text-6xl font-black text-white uppercase tracking-tighter mb-6">
              Can&apos;t Find Your <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">Exact Specs?</span>
            </h2>
            <p className="text-gray-400 text-lg md:text-xl max-w-3xl mx-auto leading-relaxed mb-10 font-medium">
              Initialize a custom procurement protocol. Tell us exactly what you need, your budget, and we will source it through our secure distribution channels.
            </p>
            
            <MagneticWrapper pullStrength={0.15}>
              <button 
                onClick={() => setIsSourcingModalOpen(true)} 
                className="px-12 py-6 bg-emerald-600 hover:bg-emerald-500 rounded-2xl font-black text-sm md:text-base uppercase tracking-widest flex items-center justify-center gap-4 transition-all shadow-[0_10px_40px_rgba(16,185,129,0.3)] hover:shadow-[0_20px_60px_rgba(16,185,129,0.5)] hover:-translate-y-1 ring-1 ring-emerald-400/50"
              >
                Initiate Sourcing Protocol <ArrowRight className="w-6 h-6 group-hover:translate-x-2 transition-transform" />
              </button>
            </MagneticWrapper>
          </div>
        </div>
      </RevealWrapper>

      {/* SWAPPED TO BOTTOM: PREMIUM HARDWARE GRID */}
      <div className="w-full max-w-6xl relative z-10 mb-20">
        <div className="flex items-center gap-4 mb-8">
            <h2 className="text-2xl font-black text-white uppercase tracking-wider">Quick-Ship Inventory</h2>
            <div className="h-px bg-white/10 flex-grow" aria-hidden="true" />
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {HARDWARE_INVENTORY.map((item, index) => (
            <RevealWrapper key={item.id} delay={index * 150} direction="up" className="h-full">
              <div 
                className="glass-card rounded-[2rem] p-8 border border-white/5 bg-gradient-to-b from-white/[0.03] to-transparent hover:border-blue-500/40 hover:bg-blue-900/10 transition-all duration-700 ease-[cubic-bezier(0.23,1,0.32,1)] group flex flex-col h-full hover:shadow-[0_20px_50px_rgba(0,163,255,0.15)] hover:-translate-y-3 relative overflow-hidden cursor-pointer" 
                onClick={() => setActiveInquiry(item)}
              >
                <div className="absolute -top-24 -right-24 w-48 h-48 bg-blue-500/20 rounded-full blur-[50px] group-hover:bg-blue-400/30 group-hover:scale-150 transition-all duration-700 pointer-events-none" />
                
                <div className="flex justify-between items-start mb-8 relative z-10">
                  <div className="w-16 h-16 rounded-2xl bg-black/50 backdrop-blur-md flex items-center justify-center border border-white/10 group-hover:border-blue-500/50 group-hover:shadow-[0_0_20px_rgba(0,163,255,0.3)] transition-all duration-500 text-gray-300 group-hover:text-blue-400">
                    {item.icon}
                  </div>
                  <div className="flex items-center gap-2 px-3 py-1.5 rounded-full bg-white/5 border border-white/10 text-[10px] font-mono uppercase tracking-widest text-gray-400 group-hover:border-blue-500/30 group-hover:text-blue-300 transition-colors">
                    {item.status === "In Stock" ? <ShieldCheck className="w-3 h-3 text-emerald-400" /> : <Zap className="w-3 h-3 text-amber-400" />}
                    {item.status}
                  </div>
                </div>

                <div className="relative z-10 flex-grow">
                  <span className="text-[10px] font-mono text-gray-500 group-hover:text-blue-400 tracking-widest uppercase mb-3 block transition-colors">{item.category}</span>
                  <h3 className="text-2xl font-bold text-white mb-4 leading-tight group-hover:text-transparent group-hover:bg-clip-text group-hover:bg-gradient-to-r group-hover:from-white group-hover:to-blue-200 transition-all">{item.name}</h3>
                </div>

                <div className="mt-8 pt-6 border-t border-white/5 group-hover:border-blue-500/20 flex items-center justify-between relative z-10 transition-colors">
                  <span className="text-xl font-black text-white tracking-wide">{item.price}</span>
                  <div className="w-10 h-10 rounded-xl bg-white/5 flex items-center justify-center group-hover:bg-blue-600 group-hover:shadow-[0_0_20px_rgba(37,99,235,0.5)] transition-all duration-500 overflow-hidden">
                    <ChevronRight className="w-5 h-5 text-gray-400 group-hover:text-white group-hover:translate-x-0.5 transition-all" />
                  </div>
                </div>
              </div>
            </RevealWrapper>
          ))}
        </div>
      </div>

      {/* ------------------------------------------------------------- */}
      {/* HUD MODAL 1: HARDWARE INQUIRY - FIXED Z-INDEX & INPUTS */}
      {/* ------------------------------------------------------------- */}
      {activeInquiry && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 sm:p-6 h-[100dvh]">
          {/* Heavy Blur Backdrop to completely hide footer/nav */}
          <div className="absolute inset-0 bg-black/95 backdrop-blur-2xl transition-opacity duration-500 animate-in fade-in" onClick={() => !isSubmitting && setActiveInquiry(null)} />
          
          <div className="w-full max-w-2xl bg-[#080808] rounded-[2rem] border border-blue-500/20 shadow-[0_0_150px_rgba(0,163,255,0.2)] relative z-10 flex flex-col max-h-[90dvh] overflow-hidden animate-in fade-in zoom-in-95 slide-in-from-bottom-12 duration-500 ease-out">
            
            <div className="p-8 md:p-10 border-b border-white/5 relative overflow-hidden shrink-0 bg-gradient-to-r from-blue-900/20 to-transparent">
              <div className="absolute -top-20 -right-20 w-64 h-64 bg-blue-500/20 rounded-full blur-[60px] pointer-events-none" />
              <button onClick={() => setActiveInquiry(null)} disabled={isSubmitting} className="absolute top-8 right-8 w-12 h-12 bg-white/5 hover:bg-white/10 hover:rotate-90 rounded-full flex items-center justify-center transition-all duration-300 backdrop-blur-md border border-white/10">
                <X className="w-6 h-6 text-gray-400" />
              </button>
              
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 rounded-xl bg-blue-500/20 flex items-center justify-center border border-blue-500/30">
                  {activeInquiry.icon}
                </div>
                <span className="text-xs font-mono text-blue-400 uppercase tracking-widest bg-blue-500/10 px-4 py-1.5 rounded-full border border-blue-500/20">Item Inquiry</span>
              </div>
              
              <h2 className="text-3xl md:text-4xl font-black text-white tracking-tight mb-3 pr-16">{activeInquiry.name}</h2>
              <div className="flex items-center gap-4 text-base font-mono text-gray-400">
                <span>{activeInquiry.category}</span>
                <span className="w-1.5 h-1.5 rounded-full bg-blue-500" />
                <span className="text-white font-bold">{activeInquiry.price}</span>
              </div>
            </div>

            <div className="overflow-y-auto p-8 md:p-10 flex-1 custom-scrollbar">
              <form id="inquiryForm" onSubmit={handleInquirySubmit} className="space-y-8">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Client Name</label>
                    <input type="text" required placeholder="Enter your full name" className="w-full bg-[#111] hover:bg-[#151515] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/60 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" value={inquiryForm.name} onChange={(e) => setInquiryForm({...inquiryForm, name: e.target.value})} />
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Email Address</label>
                    <input type="email" required placeholder="your.email@example.com" className="w-full bg-[#111] hover:bg-[#151515] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/60 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" value={inquiryForm.email} onChange={(e) => setInquiryForm({...inquiryForm, email: e.target.value})} />
                  </div>
                </div>
                <div className="space-y-3">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Phone Number (Optional)</label>
                  <input type="tel" placeholder="+27 XX XXX XXXX" className="w-full bg-[#111] hover:bg-[#151515] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/60 focus:border-blue-500 transition-all text-base placeholder:text-gray-600 shadow-inner" value={inquiryForm.phone} onChange={(e) => setInquiryForm({...inquiryForm, phone: e.target.value})} />
                </div>
                <div className="space-y-3">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Inquiry Details</label>
                  <textarea required rows={4} placeholder="Ask about stock, compatibility, or delivery times..." className="w-full bg-[#111] hover:bg-[#151515] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-blue-500/60 focus:border-blue-500 transition-all text-base resize-none placeholder:text-gray-600 shadow-inner" value={inquiryForm.message} onChange={(e) => setInquiryForm({...inquiryForm, message: e.target.value})} />
                </div>
              </form>
            </div>

            <div className="p-8 md:p-10 border-t border-white/5 bg-[#050505] shrink-0 flex items-center justify-between">
              <button type="button" onClick={() => setActiveInquiry(null)} className="text-sm font-mono text-gray-400 hover:text-white uppercase tracking-widest transition-colors px-4 py-2 hidden md:block">Cancel</button>
              
              <button form="inquiryForm" type="submit" disabled={isSubmitting} className="w-full md:w-auto px-12 py-5 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-900/50 disabled:text-blue-400/50 disabled:cursor-not-allowed rounded-2xl font-black text-sm uppercase tracking-widest flex justify-center items-center gap-3 transition-all shadow-[0_10px_30px_rgba(37,99,235,0.4)] ring-1 ring-blue-400/50 min-h-[64px]">
                {isSubmitting ? <><Loader2 className="w-6 h-6 animate-spin" /> Transmitting...</> : "Transmit Inquiry"}
              </button>
            </div>

          </div>
        </div>
      )}

      {/* ------------------------------------------------------------- */}
      {/* HUD MODAL 2: CUSTOM SOURCING - FIXED Z-INDEX & INPUTS */}
      {/* ------------------------------------------------------------- */}
      {isSourcingModalOpen && (
        <div className="fixed inset-0 z-[9999] flex items-center justify-center p-4 sm:p-6 h-[100dvh]">
          {/* Heavy Blur Backdrop */}
          <div className="absolute inset-0 bg-black/95 backdrop-blur-2xl transition-opacity duration-500 animate-in fade-in" onClick={() => !isSubmitting && setIsSourcingModalOpen(false)} />
          
          <div className="w-full max-w-3xl bg-[#080808] rounded-[2rem] border border-emerald-500/20 shadow-[0_0_150px_rgba(16,185,129,0.15)] relative z-10 flex flex-col max-h-[90dvh] overflow-hidden animate-in fade-in zoom-in-95 slide-in-from-bottom-12 duration-500 ease-out">
            
            <div className="p-8 md:p-10 border-b border-white/5 relative overflow-hidden shrink-0 bg-gradient-to-r from-emerald-900/20 to-transparent">
              <div className="absolute -top-20 -right-20 w-64 h-64 bg-emerald-500/20 rounded-full blur-[60px] pointer-events-none" />
              <button onClick={() => setIsSourcingModalOpen(false)} disabled={isSubmitting} className="absolute top-8 right-8 w-12 h-12 bg-white/5 hover:bg-white/10 hover:rotate-90 rounded-full flex items-center justify-center transition-all duration-300 backdrop-blur-md border border-white/10">
                <X className="w-6 h-6 text-gray-400" />
              </button>
              
              <div className="flex items-center gap-3 mb-6">
                <div className="w-10 h-10 rounded-xl bg-emerald-500/20 flex items-center justify-center border border-emerald-500/30">
                  <Search className="w-5 h-5 text-emerald-400" />
                </div>
                <span className="text-xs font-mono text-emerald-400 uppercase tracking-widest bg-emerald-500/10 px-4 py-1.5 rounded-full border border-emerald-500/20">Custom Procurement</span>
              </div>

              <h2 className="text-3xl md:text-4xl font-black text-white tracking-tight mb-3 pr-16">Hardware Sourcing</h2>
              <p className="text-base text-gray-400 font-medium">Activate global search protocol for specific components.</p>
            </div>

            <div className="overflow-y-auto p-8 md:p-10 flex-1 custom-scrollbar">
              <form id="sourcingForm" onSubmit={handleSourcingSubmit} className="space-y-8">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Client Name</label>
                    <input type="text" required placeholder="Full Name" className="w-full bg-[#111] hover:bg-[#151515] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/60 focus:border-emerald-500 transition-all text-base placeholder:text-gray-600 shadow-inner" value={sourcingForm.name} onChange={(e) => setSourcingForm({...sourcingForm, name: e.target.value})} />
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Email Address</label>
                    <input type="email" required placeholder="your.email@example.com" className="w-full bg-[#111] hover:bg-[#151515] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/60 focus:border-emerald-500 transition-all text-base placeholder:text-gray-600 shadow-inner" value={sourcingForm.email} onChange={(e) => setSourcingForm({...sourcingForm, email: e.target.value})} />
                  </div>
                </div>
                
                <div className="space-y-3">
                  <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Exact Part Specifications</label>
                  <textarea required rows={3} placeholder="E.g. Intel Core i9-14900K or MSI GeForce RTX 4090 Suprim X..." className="w-full bg-[#111] hover:bg-[#151515] border border-white/10 rounded-2xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/60 focus:border-emerald-500 transition-all text-base resize-none placeholder:text-gray-600 shadow-inner" value={sourcingForm.specs} onChange={(e) => setSourcingForm({...sourcingForm, specs: e.target.value})} />
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8 bg-white/5 p-8 rounded-3xl border border-white/5">
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Target Budget</label>
                    <select className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/60 focus:border-emerald-500 transition-all text-base cursor-pointer appearance-none" value={sourcingForm.budget} onChange={(e) => setSourcingForm({...sourcingForm, budget: e.target.value})}>
                      <option>Under R1,000</option>
                      <option>R1,000 - R3,000</option>
                      <option>R3,000 - R10,000</option>
                      <option>R10,000+</option>
                    </select>
                  </div>
                  <div className="space-y-3">
                    <label className="text-xs font-mono text-gray-400 uppercase tracking-widest ml-1">Acceptable Condition</label>
                    <select className="w-full bg-[#0a0a0a] border border-white/10 rounded-xl p-5 text-white focus:outline-none focus:ring-2 focus:ring-emerald-500/60 focus:border-emerald-500 transition-all text-base cursor-pointer appearance-none" value={sourcingForm.condition} onChange={(e) => setSourcingForm({...sourcingForm, condition: e.target.value})}>
                      <option>Brand New Only</option>
                      <option>New or Refurbished</option>
                      <option>Used / Second Hand</option>
                    </select>
                  </div>
                </div>
              </form>
            </div>

            <div className="p-8 md:p-10 border-t border-white/5 bg-[#050505] shrink-0 flex items-center justify-between">
              <button type="button" onClick={() => setIsSourcingModalOpen(false)} className="text-sm font-mono text-gray-400 hover:text-white uppercase tracking-widest transition-colors px-4 py-2 hidden md:block">Cancel</button>
              
              <button form="sourcingForm" type="submit" disabled={isSubmitting} className="w-full md:w-auto px-12 py-5 bg-emerald-600 hover:bg-emerald-500 disabled:bg-emerald-900/50 disabled:text-emerald-400/50 disabled:cursor-not-allowed rounded-2xl font-black text-sm uppercase tracking-widest flex justify-center items-center gap-3 transition-all shadow-[0_10px_30px_rgba(16,185,129,0.4)] ring-1 ring-emerald-400/50 min-h-[64px]">
                {isSubmitting ? <><Loader2 className="w-6 h-6 animate-spin" /> Transmitting Request...</> : "Initialize Search"}
              </button>
            </div>

          </div>
        </div>
      )}
    </>
  );
}

export default function ShopPage() {
  return (
    <main className="min-h-screen pt-32 pb-20 px-4 md:px-6 flex flex-col items-center overflow-hidden relative">
      {/* Global Background Glow */}
      <div className="absolute top-0 left-1/2 -translate-x-1/2 w-full max-w-6xl h-[600px] bg-emerald-600/5 rounded-[100%] blur-[150px] pointer-events-none z-0" aria-hidden="true" />
      <div className="scanline opacity-10 pointer-events-none absolute inset-0 z-0" aria-hidden="true" />
      
      <Suspense fallback={<div className="min-h-screen flex items-center justify-center"><Loader2 className="w-10 h-10 text-emerald-500 animate-spin" /></div>}>
        <ShopLogic />
      </Suspense>
    </main>
  );
}