"use client";
import { useState, Suspense } from "react";
import { useRouter } from "next/navigation";
import { Search, HardDrive, Cpu, Monitor, X, Loader2, ChevronRight, ArrowRight, ArrowLeft } from "lucide-react";
import DecodeText from "../components/DecodeText";
import MagneticWrapper from "../components/MagneticWrapper";
import RevealWrapper from "../components/RevealWrapper";

// Dummy Product Data
const HARDWARE_INVENTORY = [
  { id: 1, name: "Samsung 980 PRO 1TB NVMe SSD", category: "Storage", price: "R 2,499", icon: <HardDrive className="w-8 h-8" /> },
  { id: 2, name: "AMD Ryzen 7 5800X3D", category: "Processor", price: "R 6,899", icon: <Cpu className="w-8 h-8" /> },
  { id: 3, name: "ASUS ROG Strix 27\" 1440p 170Hz", category: "Display", price: "R 9,299", icon: <Monitor className="w-8 h-8" /> },
];

function ShopLogic() {
  const router = useRouter();
  
  // Modals State
  const [activeInquiry, setActiveInquiry] = useState<typeof HARDWARE_INVENTORY[0] | null>(null);
  const [isSourcingModalOpen, setIsSourcingModalOpen] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);

  // Form States
  const [inquiryForm, setInquiryForm] = useState({ name: "", email: "", phone: "", message: "" });
  const [sourcingForm, setSourcingForm] = useState({ name: "", email: "", phone: "", specs: "", budget: "R1,000 - R3,000", condition: "Brand New Only" });

  const handleInquirySubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!activeInquiry) return;
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
HARDWARE INQUIRY LOGGED
=========================================

CLIENT INFORMATION
-----------------------------------------
Name:     ${inquiryForm.name}
Email:    ${inquiryForm.email}
Phone:    ${inquiryForm.phone || 'Not Provided'}

TARGET HARDWARE
-----------------------------------------
Product:  ${activeInquiry.name}
Category: ${activeInquiry.category}
Listed:   ${activeInquiry.price}

CLIENT MESSAGE
-----------------------------------------
${inquiryForm.message || "No additional questions."}

=========================================
System Generated by The Mouton Hub
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", inquiryForm.name || "Hub Client");
      payload.append("email", inquiryForm.email || "no-reply@themoutonhub.com");
      payload.append("subject", `Hardware Inquiry: ${activeInquiry.name} - ${inquiryForm.name}`);
      payload.append("from_name", "The Mouton Hub Store");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", {
        method: "POST",
        body: payload, 
      });

      const result = await response.json();
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to transmit request. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleSourcingSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsSubmitting(true);

    try {
      const emailMessage = `
=========================================
CUSTOM SOURCING REQUEST
=========================================

CLIENT INFORMATION
-----------------------------------------
Name:     ${sourcingForm.name}
Email:    ${sourcingForm.email}
Phone:    ${sourcingForm.phone || 'Not Provided'}

SOURCING PARAMETERS
-----------------------------------------
Budget:       ${sourcingForm.budget}
Condition:    ${sourcingForm.condition}

PART SPECIFICATIONS
-----------------------------------------
${sourcingForm.specs}

=========================================
System Generated by The Mouton Hub
      `;

      const payload = new FormData();
      payload.append("access_key", "2babf3c8-9992-43c2-b422-eaa26c265417");
      payload.append("name", sourcingForm.name || "Hub Client");
      payload.append("email", sourcingForm.email || "no-reply@themoutonhub.com");
      payload.append("subject", `Custom Sourcing: ${sourcingForm.name}`);
      payload.append("from_name", "The Mouton Hub Sourcing");
      payload.append("message", emailMessage);

      const response = await fetch("https://api.web3forms.com/submit", {
        method: "POST",
        body: payload, 
      });

      const result = await response.json();
      if (result.success) {
        router.push("/success");
      } else {
        throw new Error(result.message || "Email provider rejected the submission.");
      }
    } catch (error) {
      console.error("Transmission Error:", error);
      const errorMessage = error instanceof Error ? error.message : "Network Blocked";
      alert(`System failure: Unable to transmit request. Reason: ${errorMessage}`);
    } finally {
      setIsSubmitting(false);
    }
  };

  return (
    <>
      <header className="w-full max-w-4xl mb-16 text-center relative z-10 mx-auto">
        <h1 className="text-4xl md:text-6xl font-black tracking-tighter uppercase mb-4">
          <DecodeText text="Hardware" /> <br className="md:hidden" />
          <span className="text-gradient drop-shadow-[0_0_30px_rgba(0,163,255,0.2)]">
            <DecodeText text="Procurement" delay={800} />
          </span>
        </h1>
        <RevealWrapper delay={1200} direction="up">
          <p className="text-gray-300 font-mono text-sm uppercase tracking-widest max-w-xl mx-auto leading-relaxed">
            Enterprise-grade components & custom sourcing protocols for high-performance builds.
          </p>
        </RevealWrapper>
      </header>

      {/* HARDWARE GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 w-full max-w-6xl relative z-10 mb-20">
        {HARDWARE_INVENTORY.map((item, index) => (
          <RevealWrapper key={item.id} delay={index * 150} direction="up">
            <div className="glass-card rounded-[2rem] p-8 border border-blue-500/20 hover:border-blue-500/50 transition-all duration-500 group flex flex-col h-full hover:shadow-[0_15px_40px_rgba(0,163,255,0.15)] hover:-translate-y-2 relative overflow-hidden cursor-pointer" onClick={() => setActiveInquiry(item)}>
              <div className="absolute top-0 right-0 w-32 h-32 bg-blue-500/5 rounded-full blur-2xl group-hover:scale-125 transition-transform" />
              <div className="w-16 h-16 rounded-2xl bg-white/5 flex items-center justify-center mb-6 group-hover:bg-blue-500/20 group-hover:scale-110 transition-all duration-500 border border-white/10 group-hover:border-blue-500/30 text-blue-400">
                {item.icon}
              </div>
              <span className="text-xs font-mono text-blue-400 tracking-widest uppercase mb-2">{item.category}</span>
              <h3 className="text-xl font-bold text-white mb-4 leading-tight">{item.name}</h3>
              <div className="mt-auto pt-6 border-t border-white/10 flex items-center justify-between">
                <span className="text-lg font-black text-white">{item.price}</span>
                <span className="w-8 h-8 rounded-full bg-white/5 flex items-center justify-center group-hover:bg-blue-600 transition-colors">
                  <ChevronRight className="w-4 h-4 text-white" />
                </span>
              </div>
            </div>
          </RevealWrapper>
        ))}
      </div>

      {/* CUSTOM SOURCING BANNER */}
      <RevealWrapper delay={600} className="w-full max-w-4xl relative z-10">
        <div className="glass-card rounded-[2rem] p-10 border border-emerald-500/30 shadow-[0_0_50px_rgba(16,185,129,0.1)] text-center relative overflow-hidden group">
          <div className="absolute inset-0 bg-emerald-500/5 group-hover:bg-emerald-500/10 transition-colors duration-500" />
          <div className="w-16 h-16 rounded-full bg-emerald-500/20 flex items-center justify-center mx-auto mb-6 border border-emerald-500/50 shadow-[0_0_30px_rgba(16,185,129,0.3)]">
            <Search className="w-8 h-8 text-emerald-400" />
          </div>
          <h2 className="text-2xl md:text-3xl font-black text-white uppercase tracking-wider mb-4">Can&apos;t Find Your Specs?</h2>
          <p className="text-gray-400 text-sm max-w-lg mx-auto leading-relaxed mb-8">
            Initiate a custom sourcing protocol. We leverage global and local supplier networks to find exactly what you need.
          </p>
          <MagneticWrapper pullStrength={0.1}>
            <button onClick={() => setIsSourcingModalOpen(true)} className="px-8 py-4 bg-emerald-600 hover:bg-emerald-500 rounded-xl font-black text-xs uppercase tracking-widest flex items-center justify-center gap-3 transition-all shadow-[0_10px_30px_rgba(16,185,129,0.3)] hover:shadow-[0_15px_40px_rgba(16,185,129,0.5)] mx-auto">
              Initiate Sourcing <ArrowRight className="w-4 h-4" />
            </button>
          </MagneticWrapper>
        </div>
      </RevealWrapper>

      {/* MODAL 1: HARDWARE INQUIRY */}
      {activeInquiry && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/80 backdrop-blur-md" onClick={() => !isSubmitting && setActiveInquiry(null)} />
          <div className="glass-card w-full max-w-xl rounded-[2rem] border border-blue-500/30 shadow-[0_0_50px_rgba(0,163,255,0.2)] relative z-10 flex flex-col max-h-[90vh] overflow-hidden animate-in fade-in zoom-in-95 duration-300">
            
            <div className="p-6 md:p-8 border-b border-white/10 relative overflow-hidden shrink-0">
              <div className="absolute top-0 right-0 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl pointer-events-none" />
              <button onClick={() => setActiveInquiry(null)} disabled={isSubmitting} className="absolute top-6 right-6 w-8 h-8 bg-white/5 hover:bg-white/10 rounded-full flex items-center justify-center transition-colors">
                <X className="w-4 h-4 text-gray-400" />
              </button>
              <button onClick={() => setActiveInquiry(null)} className="text-gray-400 hover:text-white mb-6 flex items-center gap-2 font-mono text-[10px] uppercase tracking-widest transition-colors w-fit"><ArrowLeft className="w-3 h-3" /> Back to Specs</button>
              <h2 className="text-2xl md:text-3xl font-black text-white uppercase tracking-wider mb-2">Hardware Inquiry</h2>
              <p className="text-sm text-gray-400">Requesting availability or details for: <span className="text-blue-400 font-bold">{activeInquiry.name}</span></p>
            </div>

            <div className="overflow-y-auto p-6 md:p-8 flex-1">
              <form id="inquiryForm" onSubmit={handleInquirySubmit} className="space-y-5">
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Your Name</label>
                  <input type="text" required className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 text-sm" value={inquiryForm.name} onChange={(e) => setInquiryForm({...inquiryForm, name: e.target.value})} />
                </div>
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Email Address</label>
                  <input type="email" required className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 text-sm" value={inquiryForm.email} onChange={(e) => setInquiryForm({...inquiryForm, email: e.target.value})} />
                </div>
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Phone (Optional)</label>
                  <input type="tel" className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 text-sm" value={inquiryForm.phone} onChange={(e) => setInquiryForm({...inquiryForm, phone: e.target.value})} />
                </div>
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Message / Questions</label>
                  <textarea required rows={4} className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-blue-500 text-sm resize-none" value={inquiryForm.message} onChange={(e) => setInquiryForm({...inquiryForm, message: e.target.value})} />
                </div>
              </form>
            </div>

            <div className="p-6 md:p-8 border-t border-white/10 bg-black/40 shrink-0">
              <button form="inquiryForm" type="submit" disabled={isSubmitting} className="w-full py-4 bg-blue-600 hover:bg-blue-500 disabled:bg-blue-900 disabled:text-blue-400 disabled:cursor-not-allowed rounded-xl font-black text-xs uppercase tracking-widest flex justify-center items-center gap-3 transition-all shadow-[0_10px_30px_rgba(0,163,255,0.3)] min-h-[56px]">
                {isSubmitting ? <><Loader2 className="w-4 h-4 animate-spin" /> Transmitting...</> : "Log Ticket"}
              </button>
            </div>

          </div>
        </div>
      )}

      {/* MODAL 2: CUSTOM SOURCING */}
      {isSourcingModalOpen && (
        <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/80 backdrop-blur-md" onClick={() => !isSubmitting && setIsSourcingModalOpen(false)} />
          <div className="glass-card w-full max-w-xl rounded-[2rem] border border-emerald-500/30 shadow-[0_0_50px_rgba(16,185,129,0.2)] relative z-10 flex flex-col max-h-[90vh] overflow-hidden animate-in fade-in zoom-in-95 duration-300">
            
            <div className="p-6 md:p-8 border-b border-white/10 relative overflow-hidden shrink-0">
              <div className="absolute top-0 right-0 w-48 h-48 bg-emerald-500/10 rounded-full blur-3xl pointer-events-none" />
              <button onClick={() => setIsSourcingModalOpen(false)} disabled={isSubmitting} className="absolute top-6 right-6 w-8 h-8 bg-white/5 hover:bg-white/10 rounded-full flex items-center justify-center transition-colors">
                <X className="w-4 h-4 text-gray-400" />
              </button>
              <h2 className="text-2xl md:text-3xl font-black text-white uppercase tracking-wider mb-2">Custom Sourcing</h2>
              <p className="text-sm text-gray-400 leading-relaxed">Deploying search protocols across local and international hardware suppliers.</p>
            </div>

            <div className="overflow-y-auto p-6 md:p-8 flex-1">
              <form id="sourcingForm" onSubmit={handleSourcingSubmit} className="space-y-5">
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Your Name</label>
                  <input type="text" required className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-emerald-500 text-sm" value={sourcingForm.name} onChange={(e) => setSourcingForm({...sourcingForm, name: e.target.value})} />
                </div>
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Your Email</label>
                  <input type="email" required className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-emerald-500 text-sm" value={sourcingForm.email} onChange={(e) => setSourcingForm({...sourcingForm, email: e.target.value})} />
                </div>
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Phone (Optional)</label>
                  <input type="tel" className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-emerald-500 text-sm" value={sourcingForm.phone} onChange={(e) => setSourcingForm({...sourcingForm, phone: e.target.value})} />
                </div>
                <div>
                  <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Part Specifications</label>
                  <textarea required rows={3} placeholder="Be as specific as possible..." className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-emerald-500 text-sm resize-none" value={sourcingForm.specs} onChange={(e) => setSourcingForm({...sourcingForm, specs: e.target.value})} />
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Budget Range</label>
                    <select className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-emerald-500 text-sm" value={sourcingForm.budget} onChange={(e) => setSourcingForm({...sourcingForm, budget: e.target.value})}>
                      <option>Under R1,000</option>
                      <option>R1,000 - R3,000</option>
                      <option>R3,000 - R10,000</option>
                      <option>R10,000+</option>
                    </select>
                  </div>
                  <div>
                    <label className="text-[10px] font-mono text-gray-400 uppercase tracking-widest mb-2 block">Condition</label>
                    <select className="w-full bg-black/60 border border-white/10 rounded-xl p-4 text-white focus:ring-2 focus:ring-emerald-500 text-sm" value={sourcingForm.condition} onChange={(e) => setSourcingForm({...sourcingForm, condition: e.target.value})}>
                      <option>Brand New Only</option>
                      <option>New or Refurbished</option>
                      <option>Used / Second Hand</option>
                    </select>
                  </div>
                </div>
              </form>
            </div>

            <div className="p-6 md:p-8 border-t border-white/10 bg-black/40 shrink-0">
              <button form="sourcingForm" type="submit" disabled={isSubmitting} className="w-full py-4 bg-emerald-600 hover:bg-emerald-500 disabled:bg-emerald-900 disabled:text-emerald-400 disabled:cursor-not-allowed rounded-xl font-black text-xs uppercase tracking-widest flex justify-center items-center gap-3 transition-all shadow-[0_10px_30px_rgba(16,185,129,0.3)] min-h-[56px]">
                {isSubmitting ? <><Loader2 className="w-4 h-4 animate-spin" /> Transmitting Request...</> : "Submit Sourcing Request"}
              </button>
            </div>

          </div>
        </div>
      )}
    </>
  );
}

export default function ShopPage() {
  return (
    <main className="min-h-screen pt-32 pb-20 px-6 flex flex-col items-center overflow-hidden relative">
      <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-blue-600/5 rounded-full blur-[120px] pointer-events-none z-0" aria-hidden="true" />
      <div className="scanline opacity-10 pointer-events-none absolute inset-0 z-0" aria-hidden="true" />
      
      <Suspense fallback={<div className="min-h-screen flex items-center justify-center"><Loader2 className="w-10 h-10 text-blue-500 animate-spin" /></div>}>
        <ShopLogic />
      </Suspense>
    </main>
  );
}